# Generated by Django 3.2.11 on 2025-01-02 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('about', models.TextField()),
                ('tickets', models.CharField(choices=[('boş', 'Lütfen bir hastalık seçiniz'), ('fıtık', 'Fıtık'), ('donuk', 'Donuk'), ('osteoartriti', 'Kireçlenme'), ('inme', 'Felç'), ('skolyoz', 'Skolyoz'), ('romatoid', 'Romatoid'), ('parkinson', 'Parkinson')], default='boş', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='uploads/')),
                ('about', models.TextField()),
                ('img', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.DurationField()),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illnesss', to='home.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField()),
                ('Title', models.CharField(max_length=50)),
                ('About', models.TextField()),
                ('Finish', models.BooleanField()),
                ('Spend', models.IntegerField()),
                ('Income', models.IntegerField()),
                ('Jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medics', to='home.medic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
