# Generated by Django 3.2.11 on 2024-12-22 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='uploads/')),
                ('img', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tickets', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField()),
                ('Title', models.CharField(max_length=50)),
                ('About', models.TextField()),
                ('Finish', models.BooleanField()),
                ('Spend', models.IntegerField()),
                ('Income', models.IntegerField()),
                ('Jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='authentication.profile')),
            ],
        ),
    ]
